### ISSUE TITLE
Giving error on site root /folder_contents

### ISSUE THREAD

**Issue by espenmn** [RedTurtle/rt.lastmodifier#3]
If you click on Content (or add /folder_contents) you will get this error:
(Plone 4.3)

Traceback (innermost last):
  Module ZPublisher.Publish, line 60, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 46, in call_object
  Module wildcard.foldercontents.views, line 149, in __call__
  Module plone.app.content.browser.foldercontents, line 49, in __call__
  Module Products.Five.browser.metaconfigure, line 476, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 149, in render
  Module chameleon.zpt.template, line 257, in render
  Module chameleon.template, line 172, in render
  Module dcaead9af4a63562d706456380b581bb19e955da.py, line 1761, in render
  Module a7d49e5ae9c709a831d9e67e7916d2d08ef7d709.py, line 1620, in render_master
  Module a7d49e5ae9c709a831d9e67e7916d2d08ef7d709.py, line 282, in render_content
  Module a7d49e5ae9c709a831d9e67e7916d2d08ef7d709.py, line 511, in render_main
  Module z3c.pt.expressions, line 61, in render_content_provider
  Module plone.app.viewletmanager.manager, line 155, in render
  Module plone.app.viewletmanager.manager, line 86, in render
  Module plone.app.layout.viewlets.common, line 50, in render
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 149, in render
  Module chameleon.zpt.template, line 257, in render
  Module chameleon.template, line 190, in render
  Module chameleon.template, line 172, in render
  Module a3bbbd791fffe520b07ec4dd73ee9c7357aa2c4d.py, line 760, in render
  Module five.pt.expressions, line 161, in __call__
  Module rt.lastmodifier.browser.changenote, line 12, in changenote
AttributeError: getField

 - Expression: "provider:plone.belowcontenttitle"
 - Filename:   main_template
 - Location:   (132:56)
 - Expression: "nocall:here/aq_explicit/widget"
 - Filename:   <string>
 - Location:   (0:0)
 - Expression: "nocall:here/aq_explicit/widget"
 - Filename:   <string>
 - Location:   (0:0)
 - Expression: "view/changenote"
 - Filename:   ... 0.4-py2.7.egg/rt/lastmodifier/browser/document_byline.pt
 - Location:   (71:51)
 - Source:     ... es tal:define="changenote view/changenote"
                                             ^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x1b568c6c>
               views: <ViewMapper - at 0xf7e390c>
               modules: <instance - at 0xa13872c>
               args: <tuple - at 0xb75ec02cL>
               here: <ImplicitAcquisitionWrapper maritme at 0x1c799cd4>
               wrapped_repeat: <SafeMapping - at 0x136bc7d4>
               user: <ImplicitAcquisitionWrapper - at 0x1c9cb75c>
               view: <SimpleViewletClass from /home/espen/instance8096/buildout-cache/eggs/rt.lastmodifier-0.4-py2.7.egg/rt/lastmodifier/browser/document_byline.pt plone.belowcontenttitle.documentbyline at 0x19ebb42c>
               nothing: <NoneType - at 0x818e5c0>
               container: <ImplicitAcquisitionWrapper maritme at 0x1c799cd4>
               request: <instance - at 0x1c9ca24c>
               modified: 2013-02-19T20:37:37+01:00
               traverse_subpath: <list - at 0x1c8f162c>
               default: <object - at 0xb760b7f8L>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper maritme at 0x1c799cd4>
               published: <NoneType - at 0x818e5c0>
               translate: <function translate at 0x1c7acf7c>
               root: <ImplicitAcquisitionWrapper Zope at 0x1c7ec6bc>
               options: {...} (0)
               target_language: <NoneType - at 0x818e5c0>

**Comment by keul** [comment]
@espenmn are you using last 0.4.1 version? This bug seems solved on that version.

**Comment by espenmn** [comment]
I use 0.4. Actually, I read the changelog for 0.4.1 and it said nothing about this, so I assumed it was not fixed. Thanks for the feedback

**Comment by keul** [comment]
@espenmn actually is the issue noted as "Fixed issue in calling @@manage-viewlets" but the problem was a lot more generic.
